site_name: NitroFE

repo_url:  https://github.com/NITRO-AI/NitroFE

nav:
  - Introduction: 'index.md'
  - Time based features:
    - indicators features: 'indicators features.md'
    - moving average features: 'moving average features.md'
    - weighted window features: 'weighted window features.md'

theme:
  name: material

plugins:
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js